sencha_ticket:
    resource: "@SenchaTicketBundle/Controller/"
    type:     annotation
    prefix:   /

oc_platform:
    resource: "@OCPlatformBundle/Resources/config/routing.yml"
    prefix:   /platform


