<?php

namespace OC\PlatformBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * AdvertRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AdvertRepository extends EntityRepository
{
	public function myFindAll()
	
	{
	
		return $this

		    ->createQueryBuilder('a')
		
		    ->getQuery()
		
		    ->getResult()
		
		  	;
	
	}
	
	public function myFindOne($id)
	
	{
	
		$qb = $this->createQueryBuilder('a');
	
		$qb
	
		->where('a.id = :id')
	
		->setParameter('id', $id)
	
		;
	
		return $qb
	
		->getQuery()
	
		->getResult()
	
		;
	
	}
	
}
